### ISSUE TITLE
Can this work with the 256*20 network trained with Leela Zero?

### ISSUE THREAD

**Issue by hydrogenpi** [CamWagner/lizzie#1]
How can I get this to work with the very strong (3500+ ELO) 256*20 network trained with Leela Zero that was published by someone a while back?

**Comment by CamWagner** [comment]
Yes. Simply replace the file called network with your own.

**Comment by hydrogenpi** [comment]
Thanks it worked. Are you planning on making this compatible with the AQ engine and the Minigo engine as well?

**Comment by CamWagner** [comment]
Not particularly. I chose Leela zero because it's open source, which let me enable additional text from pondering playouts. Without such a feature, it's difficult for me to get any information from AQ. So it works best with Leela Zero.

Minigo isn't stronger than Leelaz, right?

**Comment by hydrogenpi** [comment]
I was under the impression MiniGo, AQ, Ray/on are all open source on github. 

Can you make it like Sabaki where user can load up multiple networks /engines and select with engines/networks combo to have them play/battle out each other?

**Comment by CamWagner** [comment]
it's probably too many features for now. I am too busy to implement all of these. I just wanted an analysis tool for Leela zero similar to Leela's :). I might attach Minigo if it becomes super strong!

The interface with Leelaz is just through GTP. Any GTP program can be attached, and if it is modified to output its analysis a few times per second, it will work. If youre willing to modify a program to fit this format, I'll gladly release it.
