### ISSUE TITLE
[Problem] no rate on screen ??

### ISSUE THREAD

**Issue by korverlee** [CamWagner/lizzie#10]
![default](https://user-images.githubusercontent.com/37114479/37040341-905c9c86-2194-11e8-96a7-06cb9614e691.jpg)
i use java -jar lizzie.jar . leelaz.exe -w network and lz run correctly
why no rate on screen ??

**Comment by CamWagner** [comment]
This seems likely if you supply your own leelaz.exe. Can you verify that the leelaz.exe in your folder is the one that came with the program? The custom leelaz.exe is necessary to output data while it's thinking.
