### ISSUE TITLE
board fills when ladder fails

### ISSUE THREAD

**Issue by ThorAvaTahr** [CamWagner/lizzie#15]
I have noticed a couple of times that the board fills up (with vague red circles) in situations where there is for instance a ladder that doesnt work for the active player.

Could anybody explain what is going on there?

![image](https://user-images.githubusercontent.com/30865366/37546131-c7247962-296b-11e8-93da-5bbc1922675d.png)

**Comment by CamWagner** [comment]
I think when the policy network's top move (escaping ladder) turns out to be a disaster, the tree search more quickly examines every possible move.
