### ISSUE TITLE
Lizzie does not seem to support no-GPU version?

### ISSUE THREAD

**Issue by Manslay** [CamWagner/lizzie#3]
Hello.

I'm using CPU-only leelaz, and have my tuning file set as:

0;XgemmBatched;128;100;128;16; -DKWG=32 -DKWI=2 -DMDIMA=32 -DMDIMC=32 -DMWG=32 -DNDIMB=8 -DNDIMC=8 -DNWG=64 -DSA=0 -DSB=0 -DSTRM=0 -DSTRN=0 -DVWM=1 -DVWN=4;OpenCL: Intel(R) Corporation Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz @ 2700MHz

But Lizzie starts the tuning process from scratch trying to overwrite it with another values. Is it possible to make CPU-only version work?

**Comment by CamWagner** [comment]
I see the problem. I forgot about CPU-only version. I will fix this -- thank you!

**Comment by CamWagner** [comment]
Fixed! https://github.com/CamWagner/lizzie/releases/tag/0.2
