### ISSUE TITLE
BUG?  indistinct stonse in sub board

### ISSUE THREAD

**Issue by phiming** [CamWagner/lizzie#390]
![4](https://user-images.githubusercontent.com/35087044/46571774-db441f00-c9ad-11e8-90a5-b88b241f7d5e.JPG)

The next branch.  is it intended?

**Comment by featurecat** [comment]
oh.. the stones look very funny. this happens by default? also is this recent or has been happening for a while?

**Comment by OlivierBlanvillain** [comment]
@phiming Could you bisect it?

**Comment by phiming** [comment]
@OlivierBlanvillain 
It seems that my newest branch is something wrong. I go back to my early branch(use mouse to navigate variations), there is no such problem.
Sorry, I will close this issue after I check it again.
