### ISSUE TITLE
memory overflow？？？

### ISSUE THREAD

**Issue by tanguocn** [CamWagner/lizzie#6]
That lizzie, after a long time running,  finally, the machine can not run, and even crash, collapse
Some people say this is memory overflow!

leelazero has the same problem if run it  without noponder.

so ,could you add noponder mennu command?

**Comment by CamWagner** [comment]
Yes, I'm seeing this issue too. I'll fix this for the next update. Does your program crash, or just slow down? Sometimes, with many playouts, it currently takes a while to move to the next move.

**Comment by CamWagner** [comment]
I think I've discovered the source of the bug. The program could not parse passes, so eventually when those are encountered by the search, it stops pondering. I added support for this, and Leelaz will now think for no more than a certain number of minutes to avoid excessive pondering.

**Comment by tanguocn** [comment]
that is ok.  Thx!
