### ISSUE TITLE
Some little suggestions

### ISSUE THREAD

**Issue by MingWR** [CamWagner/lizzie#7]
1. Add more key controls, e.g. P for pausing analysis, R for resuming analysis.

2. The default window size is 800 x 600, I recommend something like 800 x 770, since the tittle bar on win 10 is 30px height.

3. Make lz stop thinking after searching certain amount of visits or playouts, e.g. 2,000,000 visit. Just to make sure if anyone forget to quit the app, it won't keep running forever.

I guess All my suggestions here can be achieved in a few minutes. I really hope you can consider these.

**Comment by CamWagner** [comment]
I have implemented your suggestions and will release soon :)

Thanks!

**Comment by MingWR** [comment]
@CamWagner Thank you for taking my suggestions! I just find I made a mistake on the second one. The height should be 30px more than the width not less, then the margin of the board from top, bottom, left, and right should be all the same.

**Comment by ayssia** [comment]
I don't think we need 2 keys to pause/resume, press same key to pause, then press it again to resume is much easier.

**Comment by CamWagner** [comment]
Yeah I just used space bar :)
