### ISSUE TITLE
About saving images

### ISSUE THREAD

**Issue by hope366** [CamWagner/lizzie#767]
[Here's](https://github.com/featurecat/lizzie/pull/568) how to save lizzie as an image, but I couldn't reproduce it well.
* setting the board size to 3
* turn off the move nubmer and stone indicator
* Limit Best Move Num

After reading this description, I set the board size to 3x3 and the Best Move Num to "false". What does the stone indicator display mean?
Nothing happened with Alt + S.
Please let me know if anyone knows.

**Comment by simonguoxm** [comment]
I tried a simple game on 7x7 board. Nothing happened with Alt+S. 
Is "Save as image" feature available ?

**Comment by kaorahi** [comment]
#565 works only in Panel UI. So you need to click Settings > View > Panel UI and restart Lizzie before trying Alt+S. This is undocumented (and Alt+S itself is also undocumented).

@hope366, you should set Settings > View > Limit Best Move Number as 3 to try #568. Settings > Theme > Stone Indicator Type is the mark on the last move.

**Comment by hope366** [comment]
Thank you for letting me know.
Was the panel UI like ... I didn't notice. If nothing happens in normal mode, I decided that it was a problem and looked at the following location in Input.java.
![yy](https://user-images.githubusercontent.com/63999713/94923284-91d42f00-04f6-11eb-8455-2cc8fa4cd8ba.jpg)
I don't have any programming knowledge, but I think I could have noticed if there was a description of "panel UI" in the source code.
