### ISSUE TITLE
About sub-Go board

### ISSUE THREAD

**Issue by hebaeba** [CamWagner/lizzie#769]
With Lizzie-v0.7.4, the sub-Go board does not get bigger when clicked.
Is there a way to fix this?

**Comment by hebaeba** [comment]
This feature seems to have become the default.
I misunderstood.
Close ISSUES.

**Comment by kaorahi** [comment]
You can click the "center button" of the mouse on the subboard to toggle its size after #650. This is undocumented, as usual. :(

**Comment by hebaeba** [comment]
I use a gaming mouse, so I used the center button as the Tab key.
I reverted to the defaults and the sub-go board is now bigger. Thanks for your kindness.
