### ISSUE TITLE
Very trivial problem with mouse operation

### ISSUE THREAD

**Issue by hope366** [CamWagner/lizzie#772]
Arrange some stones in Lizzie and then put them back.
Next, try placing the stone in the same place as before. You can do it by left-clicking or using the mouse wheel. This is the case in normal mode, but in panel UI mode, stones are not displayed just by left-clicking. Only after left-clicking and moving the mouse cursor will the stone appear.
It's okay to use the mouse wheel, but I'm curious because I always operate Lizzie with the left and right mouse clicks.

Next, there is a problem with the operation of "undoing" with Leela Zero set in the engine.
If you try to undo the operation by right-clicking, it will not work on the main board, so you need to do it somewhere other than the main board. In panel UI mode, right-clicking outside the mainboard does nothing, so you are limited to using the "↑" or mouse wheel (with the exception of the top of the subboard).
Personally, I feel that right-clicking is the easiest way to undo, so it's a very trivial matter, but it's awkward to use.

**Comment by kaorahi** [comment]
See #773.

I also noticed another bug that Lizzie fails in lz-analyze if Settings > Engine > Avoid Keep Variations is 0.

~~~
$ echo 'lz-analyze 10 avoid b d4 0' | ./leelaz -g -w network.gz 2> /dev/null
? cannot parse analyze tags
~~~

So the above PR disables the allow/avoid menu by right-click in this case. Namely, you can set Settings > Engine > Avoid Keep Variations as 0 if you never want to use it. Then right-click works as "undo" even on the main board with Leela Zero.

(See also #775 for the meaning of "Avoid Keep Variations".)

**Comment by hope366** [comment]
Thank you for writing the source code. I was able to confirm the operation of all.
I've always been worried that I couldn't "undo" by right-clicking on the main board, so I'm very happy to add this feature.

I heard that there is a bug related to lz-analyze, but I couldn't confirm it. Is it a bug related to internal behavior that you don't mind when using lizzie normally?

**Comment by kaorahi** [comment]
To reproduce the bug...

1. Select Leela Zero as the engine.
2. Set Settings > Engine > Avoid Keep Variations as 0.
3. Right-click the main board and select "avoid".

Then the analysis is stopped and no suggestion is shown on the board. I expect some suggested moves should appear on the board, no matter what the above "0" means.

**Comment by hope366** [comment]
I'm sorry, maybe I was misunderstanding.
[Disable "Avoid Keep Variations" if it is 0 (ref. featurecat#772)](https://github.com/kaorahi/lizzie/commit/9cd6bafd89ac07f65a471070a14d53999270e7ad)
I thought it was after applying this, but it's not.
Before applying, yes, as you said, set "Avoid Keep Variations" to "0" and select "avoid" to stop the analysis and display the suggested assumptions. Also, there is a slight problem with the drawing on the board.
When you move the mouse cursor, the assumed figure disappears. From there, tapping the spacebar twice started the analysis.

**Comment by NTUST-MITLAB** [comment]
"Avoid Keep Variations" or as the original lz-analyze avoid parameter "number_of_moves" https://github.com/leela-zero/leela-zero/pull/1949 (or in katago lz-analyze UNTILDEPTH) is meant to be a feature to avoid certain opening fuseki, like Sanrensei fuseki, start with Tengen, or force the engine to self-play at least certain number of moves (like using avoid pass 90), hence the name "avoid some moves or pass until a certain number of moves had been analyzed". Later on the absolute "number_of_moves" from the start of a game is changed to relative to the current move hence it is named as "avoid analyzing this location until certain depth after the current move". 

A more comprehensive name for this is "generating variations while avoiding this location until after a certain number of moves",  so its value is never meant to be 0 (if it is 0, then it makes avoid void, and just a normal lz-anlyze variation generation). It makes sense to turn off this feature altogether if it is 0.
