### ISSUE TITLE
Writing and Viewing Comments

### ISSUE THREAD

**Issue by hope366** [CamWagner/lizzie#806]
If you load a file that contains comments, you can see them in the comments section, but I'm Japanese so I can't read them if they are written in Chinese.
It's very difficult to decipher as you can't copy and paste.
Next, let's talk about how to write your own comments.
I have a notepad so I can edit it, but this method is quite tedious. lizzie would be very useful if you can use it to enter any comment you want on any aspect of the page.

**Comment by kaorahi** [comment]
This issue may be related to #696. @toomasr, do you have interest?

**Comment by toomasr** [comment]
@kaorahi Yeah, you are correct. I have converted this into a textarea and it is easy to make it changeable. Do you happen to know what is the easiest way to save the changes to the SGF node or you have not done it either in Lizzie?

**Comment by kaorahi** [comment]
The easiest way? Are you talking about `Lizzie.board.getHistory().getData().comment`? I've done nothing on this issue by myself.
