### ISSUE TITLE
Using KataGo's analysis engine

### ISSUE THREAD

**Issue by hope366** [CamWagner/lizzie#818]
Is lizzie made to use katago's analysis engine?
If so, how do you specifically set it up to use the analytics engine?

**Comment by infinity0** [comment]
Not sure about the custom analysis engine of KataGo but the standard GTP engine works. E.g. configure an engine inside lizzie with the command:

~~~~
/path/to/katago gtp -model g170-b40c256x2-s5095420928-d1229425124/model.bin.gz -config katago.git/cpp/configs/gtp_example.cfg
~~~~

**Comment by hope366** [comment]
Thank you for reading my post.
As for the GTP engine, I can use it without any trouble.
[KataGo description](https://github.com/lightvector/KataGo/blob/master/docs/Analysis_Engine.md) states that the analysis engine is faster than the GTP engine.
KaTrain seems to use KataGo's analysis engine, so it would be interesting if lizzie could do the same.
