### ISSUE TITLE
Set region of interest like KaTrain 1.7

### ISSUE THREAD

**Issue by kaorahi** [CamWagner/lizzie#828]
KaTrain 1.7 has a new nice feature "Set region of interest". As a quick experiment, I imported it to Lizzie with VERY BAD PROGRAMMING STYLE. We need overall rewriting if we will support it officially. But I don't have enough energy now.

~~It doesn't work in Panel UI at present.~~

Usage:

* Alt+drag to set region of interest.
* Alt+click to reset it.

https://github.com/kaorahi/lizzie/tree/allow0

**Comment by kaorahi** [comment]
We may prefer `untilDepth = 1` like the released version of KaTrain 1.7 rather than 9999.

**Comment by hope366** [comment]
The screenshot on the left is `untilDepth = 9999` and the screenshot on the right is`untilDepth = 1`.
Does "untilDepth" mean something like this?
Is `untilDepth = 9999` more useful if you want to solve "Tsumego" where only partial answers make sense?
<img src="https://user-images.githubusercontent.com/63999713/102689307-6b45aa80-4240-11eb-8c29-fd9008ed314f.png" width="40%">       <img src="https://user-images.githubusercontent.com/63999713/102689310-700a5e80-4240-11eb-83c4-7f83b99b33aa.png" width="40%">

**Comment by kaorahi** [comment]
For example, if we set `untilDepth = 3`, the restricted region is only applied until the third move. I'm afraid `untilDepth = 9999` may cause unreasonable variations. One can never capture stones by a ladder (Shicho)!

BTW, it also works in PanelUI now.

**Comment by hope366** [comment]
It is difficult to grasp how applying up to the nth movement is expressed on the board.
`untilDepth = 9999`,` untilDepth = 1`
The difference between the two, as far as the screenshots are concerned, is whether the change diagram on the board is confined to a restricted area.
Does `untilDepth = 1` apply to the first move? It's hard to see how this will be shown on the board.
>BTW, it also works in PanelUI now.

Thank you.

**Comment by youjh72** [comment]
Thanks you for your amazing effort. I am wondering about what is the difference between 'PanelUI' and normal.
I didn't know the difference when I checked the Panel UI in Lizzie settings.
Thanks in advance.

**Comment by hope366** [comment]
In panel UI mode, you can separate each panel and customize its size and position individually.
Press "Alt + W" to enter design mode.
You can separate the panels by dragging each panel with the mouse in design mode.
To restore it, click the "x" at the top right of each panel.
![無題](https://user-images.githubusercontent.com/63999713/102878072-0d58d300-448b-11eb-8dea-b7590479e633.png)

**Comment by youjh72** [comment]
Thank you very much for your kind reply.
I am very happy to use your Lizzie-improvements.
Thanks again.

**Comment by kaorahi** [comment]
See #833
