### ISSUE TITLE
Problems after applying "Set region of interest"

### ISSUE THREAD

**Issue by hope366** [CamWagner/lizzie#831]
After applying "Set region of interest", there was a report that it became impossible to switch the enlargement / reduction of the winning percentage graph by clicking the mouse wheel.
https://github.com/hope366/Lizzie-improvements/issues/5
At the same time, it seems that you can specify the analysis area by dragging the mouse wheel.
These phenomena do not occur in my environment.
It may happen under certain circumstances, but I'm not sure.
Lizzie-improvements has a lot of PR applied, so there may be conflicts and side effects, but it's difficult for me to figure out.

**Comment by kaorahi** [comment]
@wonsiks, would you try 968cdaa5 ?

link: #828

**Comment by wonsiks** [comment]
@kaorahi Do I have to compile java?

**Comment by kaorahi** [comment]
Yes. I cannot offer its binary as I have no Windows machine. If compiling is not easy for you, I expect @hope366 may help us. ;)

I guess your wheel-click is mapped to "alt + middle button" for some reason. Are you using any tool to remap mouse actions? Anyway, by 968cdaa5, the region feature only watches "alt + left button" and ignores other buttons.

**Comment by hope366** [comment]
@wonsiks I have created a jar file with [`968cdaa`](https://github.com/featurecat/lizzie/commit/968cdaa5b642c0cfee3a293f10f56dfb036b2819) applied, so please try it.
https://drive.google.com/file/d/1G58K_CpO4Rk7CywYe0vuQI1siT6Zg3fX/view?usp=sharing

**Comment by wonsiks** [comment]
@kaorahi I'm not using any kind of mouse button mapping app or something.
And there's still no problem with prior version of Lizzie but current version works differently.

I'll try to use the @hope366's binary.

Thanks.

**Comment by wonsiks** [comment]
@hope366 Yes, it works fine now.
Thank you...:)
