### ISSUE TITLE
The display at the bottom left disappears

### ISSUE THREAD

**Issue by hope366** [CamWagner/lizzie#851]
There is a display "hold x = view controls" in the lower left, but it disappears after using this function once.
It's a trivial problem, but I'd appreciate it if you could fix it.

**Comment by kaorahi** [comment]
This is not a bug but an intended behavior. (See `userAlreadyKnowsAboutCommandString` in LizzieFrame.java and BoardPane.java.)

**Comment by hope366** [comment]
It was surprising that it was intentional.
It feels more natural to be displayed all the time ...
