### ISSUE TITLE
Suddenly warp to a node in the past

### ISSUE THREAD

**Issue by hope366** [CamWagner/lizzie#858]
I have applied almost all the pull requests published here to the master of 0.7.4 and managed it as Lizzie-improvements.
https://github.com/hope366/Lizzie-improvements
There is a problem with lizzie-improved-v2.3.jar managed here. I've been aware of it for some time now, so I can't tell exactly which version is causing this bug.

Specifically, regardless of whether pondering is on or off, if you place a stone normally, it may suddenly move to a node in the past. It happens rather often, not very rarely.
We will inform you about the state of the GTP console when this phenomenon occurs.
Many unintended "undo" are displayed in succession.
![無題](https://user-images.githubusercontent.com/63999713/106551683-3c1e8c00-64c2-11eb-9fa9-5ec5e381debc.png)
I haven't done much validation, but apparently this symptom only happens in panel UI mode.
Is it related to #667?

**Comment by yzyray** [comment]
If you're using Panel UI,it maybe caused by mouse drag event in boardpane.this event will also triggle winrategraph's drag event and leads to goto some move privious or later.
I have fixed it here https://github.com/yzyray/lizzie/tree/fix_drag
You can try if it fix your issue

**Comment by hope366** [comment]
Thank you for creating the correction code.
I tried https://github.com/yzyray/lizzie/tree/fix_drag.
The problem seems to have been solved brilliantly!It's a wonderful ability.
I was very happy because I didn't expect it to be resolved so quickly 😄
thank you very much.
