### ISSUE TITLE
Disable Territory Estimate and Show Dead Stones?

### ISSUE THREAD

**Issue by Sadaharu2624** [CamWagner/lizzie#876]
Sorry for asking a very simple question but... Is it possible to disable the estimate of the territory and the showing of dead stones during analysis? I'm talking about displaying on the board itself because it's kind of distracting especially when it keeps changing.

I tried searching for the options in Lizzie but couldn't find the suitable one.
Sorry if this has been asked before.

**Comment by hope366** [comment]
Click "KataEstimate" on the bottom toolbar or use the keyboard ". " to show/hide it.

**Comment by Sadaharu2624** [comment]
> Click "KataEstimate" on the bottom toolbar or use the keyboard ". " to show/hide it.

Thanks!
