### ISSUE TITLE
Where is language switcher?

### ISSUE THREAD

**Issue by krv76** [CamWagner/lizzie#883]
I don't see any option to revert interface back to english. 
BTW, in russian some strings are cutted and in some cases russian text meaning is not obvious so I prefer english interface.

**Comment by hope366** [comment]
You can start it in English by opening a command prompt, navigating to the folder where lizzie.jar is, and then running "java -jar -Duser.language = English lizzie.jar".
It would be nice to be able to launch the English version by double-clicking, but I don't know how to launch the English version by default in an environment where the Russian version launches by default.

**Comment by krv76** [comment]
hope366, thank you!
