### ISSUE TITLE
Analytical anomaly with SGF with fixed stone placement 

### ISSUE THREAD

**Issue by hope366** [CamWagner/lizzie#889]
I will explain how to reproduce this bug.
1. Register multiple engines in lizzie in advance.For example, katago-eigen, katago-eigenavx2, katago-opencl, leelazero, etc. You may register multiple items with exactly the same contents.
1. Prepare an SGF with a fixed stone arrangement instead of a normal SGF. Please use the following SGF this time. 
(; AP [MultiGo: 4.2.4] SZ [19] MULTIGOGM [1]
AB [dd] [qd] AW [dp] [pp])
1. After starting lizzie, load the above SGF and analyze it. You should probably see a number around 50%. 
1. Then switch to another engine. At this time, a value exceeding 90% should be displayed. (It should be around 50% originally) 

Also, this bug may or may not occur due to subtle changes in the placement of the stones. For example, the SGF below did not have this bug.
(; AP [MultiGo: 4.2.4] SZ [19] MULTIGOGM [1]
AB [dd] [pd] AW [dp] [pp]) 

This bug occurred in all three types of lizzie: lizzie0.7.3, Lizzie-patched-0.7.4_210704b, Lizzie-improved-v2.7.
The engines I used for verification are katago1.9.1eigen,katago1.9.1eigenavx2, katago1.9.1opencl, leelazero0.17. We were able to confirm this bug in all these engines.  
We have only verified it in a Windows 10 environment.

**Comment by hebaeba** [comment]
After launching Lizzie, this bug seems to occur when loading a SGF with fixed stone placement and then switching engines.
The same bug occurred when I first selected katago (GPU), loaded the SGF above, and then changed to katago-eigen.
Thus, it seems to be independent of the engine type.
