### ISSUE TITLE
About "play sound" 

### ISSUE THREAD

**Issue by hope366** [CamWagner/lizzie#891]
Applying #651, there is sound in the Windows environment, but it seems that there is no sound in Mac and Linux.
So there was a suggestion for [#17](https://github.com/hope366/Lizzie-improvements/pull/17/commits/b39f71c144179c3cdc242ccd998294b3a87cbbc2), and I tried applying it, but there are still reports that there is no sound under the Mac environment. (Unknown about Linux) 

There is an opinion that "/ sound" (absolute path from the root) is the cause, and "./sound" (relative path) may work. 
I tried a little with my own wisdom, but it didn't work.
Could someone please fix it well?

**Comment by kaorahi** [comment]
This patch may help diagnosis by additional messages for sound errors.

~~~
--- a/src/main/java/featurecat/lizzie/util/Utils.java
+++ b/src/main/java/featurecat/lizzie/util/Utils.java
@@ -389,7 +389,14 @@ public class Utils {
       } catch (Exception e) {
         JOptionPane.showMessageDialog(
             Lizzie.frame,
-            resourceBundle.getString("Utils.playSound.noFileHint") + " \"" + wav + "\"");
+            resourceBundle.getString("Utils.playSound.noFileHint")
+                + " \""
+                + wav
+                + "\""
+                + "\n\n"
+                + e.getClass().getName()
+                + ": "
+                + e.getMessage());
         Lizzie.config.togglePlaySound();
         return;
       }
~~~

**Comment by hope366** [comment]
Thank you for helping me solve the problem.
I'd like to use this immediately to see what kind of error message is displayed.

**Comment by hope366** [comment]
The problem seems to have been resolved.
When starting lizzie, it seems that a problem occurred because the directory of lizzie was not set to the current directory. 
`java -jar lizzie / lizzie-0.7.4-shaded.jar`
It seems that it failed by starting like this.
`cd lizzie`
`java -jar lizzie-0.7.4-shaded.jar ` 
It is said that the sound was produced safely by starting in this way.
I think your advice was helpful. Thank you very much.
