### ISSUE TITLE
Analysis

### ISSUE THREAD

**Issue by bohemianatlarge** [CamWagner/lizzie#892]
Maybe this is an issue or maybe not. How can I save the file to sgf without all of the analysis added to the file, as this can make for very large cumbersome sgf files when there are a lot of branches to the trees that I am working on. I just want the moves and their variations I don't want all of the lines and lines of analysis. Thanks

**Comment by kaorahi** [comment]
Do you mean Settings > View > Hold Best Moves To Sgf ?

**Comment by bohemianatlarge** [comment]
I am not sure I have not tried that. I just want to be able to save what I am working on to an SGF file without it adding all that extra information to the file. If that does the trick than thanks!

Unticking the box and saving the file eliminates all the extra info being saved to the file! Thanks mate!
