### ISSUE TITLE
How to display the upper frame in Japanese 

### ISSUE THREAD

**Issue by hope366** [CamWagner/lizzie#894]
I wanted to make the top frame "### playouts, ### visits/second" in Japanese.
Line 264 of LizzieFrame.java
`"%s%d playouts,%d visits/second",`
I changed this as follows.
`"%s%d resourceBundle.getString("LizzieFrame.playouts"),%d resourceBundle.getString("LizzieFrame.visits")",`
Of course, I added the necessary code to DisplayStrings.properties and DisplayStrings_ja_JP.properties.
But this resulted in an error at compile time.

Then I tried the following:
`"%s%d プレイアウト,%d 訪問/秒",`
It compiles successfully, but what I actually see is English instead of Japanese (failure) 

It didn't work with the amateur livelihood method 😅 
I would be grateful if you could tell me if there is a good way.

**Comment by kaorahi** [comment]
It should be something like this. (not tested)

~~~
              visitsString =
                  String.format(
                      " %s%d %s, %d %s",
                      backgroundTotalPlayoutsString,
                      displayedTotalPlayouts,
                      resourceBundle.getString("LizzieFrame.playouts"),
                      (totalPlayouts > lastPlayouts) ? totalPlayouts - lastPlayouts : 0,
                      resourceBundle.getString("LizzieFrame.visits"));
~~~

You need to modify both LizzieFrame.java (normal UI) and LizzieMain.java (panel UI).

**Comment by hope366** [comment]
Thank you for letting me know.
I would like to try it immediately.

**Comment by hope366** [comment]
It went well.
`resourceBundle.getString ("LizzieFrame.visits"));`
I got an error saying that there is no ";" in this line, but the line immediately above is
`(totalPlayouts> lastPlayouts)? totalPlayouts --lastPlayouts: 0);`
It was because it was like this.
`(totalPlayouts> lastPlayouts)? totalPlayouts --lastPlayouts: 0,`
Writing it correctly like this worked.
It's probably a matter of course for programmers. 

![無題](https://user-images.githubusercontent.com/63999713/131141593-b22e47d9-41a0-427a-9197-ba1a0a8533a2.png)
