### ISSUE TITLE
Lizzie not compiling properly on ubuntu?

### ISSUE THREAD

**Issue by kombofuud** [CamWagner/lizzie#902]
I am trying to set up lizzie on my ubuntu os and I was unable to run the lizzie.jar file properly after compiling leela. The command line gave me this error mesage:

$ java -jar lizzie.jar
Gtk-Message: 19:53:37.074: Failed to load module "canberra-gtk-module"
en
Engine process ended.

And the gui gave me this:
![Screenshot from 2021-11-01 19-59-39](https://user-images.githubusercontent.com/91675728/139770077-1817421a-616c-4f5d-8e97-34728c208250.png)
![Screenshot from 2021-11-01 20-00-04](https://user-images.githubusercontent.com/91675728/139770078-58783ce1-2081-4a7a-849a-1983a04a269f.png)

Thanks for any help you can give me

**Comment by kaorahi** [comment]
You seem to have two issues.

(1)
Google says the following command for canberra-gtk-module.

~~~
sudo apt-get install libcanberra-gtk3-module
~~~

(2)
It will be better to try Leela Zero without Lizzie to fix the engine issue (or OpenCL issue). In my case (without GPU):

    $ echo name | ./leelaz -g -w lznetwork.gz
    Using 8 thread(s).
    RNG seed: 17844403544091439673
    BLAS Core: built-in Eigen 3.3.7 library.
    Detecting residual layers...v1...192 channels...15 blocks.
    Initializing CPU-only evaluation.
    Setting max tree size to 4324 MiB and cache size to 480 MiB.
    = Leela Zero
    
    
    $

You may get some hints by...

~~~
$ sudo apt-get install clinfo
$ clinfo
~~~

(Additional notes)

* The official Lizzie 0.7.4 has critical bugs (#768). They are fixed in Debian's liblizzie-java package (I guess it is also available in Ubuntu). Much more bugs are fixed further in #798.
* [KataGo](https://github.com/lightvector/KataGo) is more popular than Leela Zero nowadays because of its strength and convenient features.

**Comment by kombofuud** [comment]
After running the first two commands, I got the following:
![Screenshot from 2021-11-02 15-30-11](https://user-images.githubusercontent.com/91675728/139947461-a21c1660-205e-4b08-b66f-9cc01a092b77.png)
![Screenshot from 2021-11-02 15-30-50](https://user-images.githubusercontent.com/91675728/139947470-3868ed09-3fae-4845-bed3-3ed3f30c0bdc.png)
I think that the canberra package was already installed, but maybe if I copied it to a folder with the name canberra-gtk-module it might work? I don't know where it gets installed though.

After running clinfo, it seems that there are no platforms supported.
![Screenshot from 2021-11-02 15-35-01](https://user-images.githubusercontent.com/91675728/139947826-8892787c-2edc-4a46-a9ca-bc8fce1a0e11.png)
Even after doing a google search, and trying to connect stuff, the output from running the command is the same, but maybe I just need to connect that?

Some potentially useful to know outputs that I got were as follows:
![Screenshot from 2021-11-02 15-48-25](https://user-images.githubusercontent.com/91675728/139949436-c7d08014-7b4b-4ebc-8647-933d342baa49.png)
![Screenshot from 2021-11-02 15-49-41](https://user-images.githubusercontent.com/91675728/139949614-269c9521-ef11-48a0-819a-287a5af789ff.png)
![Screenshot from 2021-11-02 15-51-05](https://user-images.githubusercontent.com/91675728/139949819-d672fe19-4b9c-46c6-b58b-082f0582a016.png)

Thanks for any help you can give me

**Comment by kaorahi** [comment]
Searching `Gtk-Message: Failed to load module canberra-gtk-module`, I get several web pages (Ask Ubuntu, etc.) but I am not sure which is useful for you. Anyway, clinfo issue seems more critical than this.

So you may want to ask about clinfo somewhere else as it is not specific to Lizzie.
