### ISSUE TITLE
About the Color of the Outer Circle of Candidate Moves

### ISSUE THREAD

**Issue by hope366** [CamWagner/lizzie#913]
A candidate move circle may be surrounded by a red or purple circle. When does this appear?
Based on my experience, this display often appears relatively soon after the analysis starts. As the amount of analysis increases, most of them disappear.
![無題](https://user-images.githubusercontent.com/63999713/200755287-d0c8ebf5-d15e-44e4-8aca-20ad573bccd9.png)

**Comment by kaorahi** [comment]
red ring = best move. blue ring = highest winrate. The rings vanish when they are the same move.

cf. #230, drawLeelazSuggestionsBackgroundCircle in BoardRenderer.java

https://github.com/featurecat/lizzie/blob/58cfe3a4a312917f77c9b622b6ff4b82180cf5db/src/main/java/featurecat/lizzie/gui/BoardRenderer.java#L930

**Comment by hope366** [comment]
Thank you for your explanation.
After your explanation, I have one suggestion.

The ring disappears when the best move and the highest win rate are the same, but what about giving the best move in this state a wonderful colored ring?
This is because I feel that the candidate with the same best move and highest win rate is the "absolute move".

By the way, is the 'best move' shown in bluespot the 'most visited move'? (This might be something to ask in the Go AI Engine repository)

**Comment by kaorahi** [comment]
The ring of the "absolute move" seems too verbose for me.

~~~
--- a/src/main/java/featurecat/lizzie/gui/BoardRenderer.java
+++ b/src/main/java/featurecat/lizzie/gui/BoardRenderer.java
@@ -924,8 +924,7 @@ public class BoardRenderer {
           strokeWidth = 2;
           if (textData.isBestMove) {
             if (textData.hasMaxWinrate) {
-              g.setColor(textData.circleColor.darker());
-              strokeWidth = 1;
+              g.setColor(Color.MAGENTA);
             } else {
               g.setColor(Color.RED.brighter());
             }
~~~

See this page if you want to try other colors.

https://docs.oracle.com/javase/jp/8/docs/api/java/awt/Color.html

The best move is not the most visited move. It is determined from visits, winrate, score, etc. The details depend on the engine. (keywords: LCB, utility)

**Comment by hope366** [comment]
Thank you for teaching me many things.
I tried colors other than magenta, but I couldn't find a suitable color.
Having three different rings can certainly be redundant, but I think it's not such a bad idea to highlight absolute motion.

![無題](https://user-images.githubusercontent.com/63999713/201790897-747a12e6-4fe0-4a42-8c71-6fed4f500b03.png)

I vaguely understand LCB, but utility is a elusive word.
The word "utility" came up when I was investigating the information output when running KataGo on Sabaki, but I didn't understand it correctly.
